export const authTypes = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    CLEAR_CURRENT_USER: "CLEAR_CURRENT_USER"
};

export const usersTypes = {
    CREATE_USER: "CREATE_USER",
    DELETE_USER: "DELETE_USER",
    UPDATE_USER: "UPDATE_USER",
    GET_USERS_DATA: "GET_USERS_DATA",
    SET_USERS: "SET_USERS",
    SEARCH_USERS: "SEARCH_USERS"
};

export const departmentTypes = {
    GET_DEPARTMENTS: "GET_DEPARTMENTS",
    SET_DEPARTMENTS: "SET_DEPARTMENTS"
};

export const modalTypes = {
    SET_MODAL_CONTENT: "SET_MODAL_CONTENT",
    CLEAR_MODAL_CONTENT: "CLEAR_MODAL_CONTENT"
};
