export const authTypes = {
    SET_CURRENT_USER: "SET_CURRENT_USER",
    CLEAR_CURRENT_USER: "CLEAR_CURRENT_USER"
};

export const usersTypes = {
    GET_USERS_DATA:"GET_USERS_DATA",
    DELETE_USER:"DELETE_USER",
    UPDATE_USER:"UPDATE_USER",
    SET_USERS: "SET_USERS",
    SET_USER_DEPARTMENTS: "SET_USER_DEPARTMENTS"
};

export const modalTypes = {
    SET_MODAL_CONTENT: "SET_MODAL_CONTENT",
    CLEAR_MODAL_CONTENT: "CLEAR_MODAL_CONTENT"
};
